language: generic
services: docker
install:
  - |
    if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
      echo "$DOCKER_HUB_PASSWORD" |
        docker login --username stephanmisc --password-stdin
    fi
  - ./install.sh
script:
  - |
    if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
      WRITE_REMOTE_CACHE=true
    else
      WRITE_REMOTE_CACHE=false
    fi
    toast build test lint release \
      --repo stephanmisc/toast \
      --read-remote-cache true \
      --write-remote-cache "$WRITE_REMOTE_CACHE"
  - TOAST="$(pwd)/artifacts/toast-x86_64-unknown-linux-gnu" ./integration-tests.sh
