[package]
name = "bake"
version = "0.1.0"
authors = ["Stephan Boyer <stephan@stephanboyer.com>"]
edition = "2018"

[dependencies]
env_logger = "0.6"
fs_extra = "1"
hex = "0.3"
log = "0.4"
serde_yaml = "0.8"
sha2 = "0.8"
tempdir = "0.3"

[dependencies.clap]
version = "2"
default-features = true
features = ["wrap_help"]

[dependencies.serde]
version = "1"
features = ["derive"]
