[package]
name = "bake"
version = "0.1.0"
authors = ["Stephan Boyer <stephan@stephanboyer.com>"]
edition = "2018"

[dependencies]
ctrlc = "3"
env_logger = "0.6"
hex = "0.3"
log = "0.4"
rayon = "1"
scopeguard = "1"
serde_yaml = "0.8"
sha2 = "0.8"
tempfile = "3"
textwrap = "0.11"

[dependencies.clap]
version = "2"
default-features = true
features = ["wrap_help"]

[dependencies.serde]
version = "1"
features = ["derive"]
